### ISSUE TITLE
Nuget package not found.

### ISSUE THREAD

**Issue by jeffersonking** [microsoft/vssdktestfx#1]
Is this an internal-only package? We work on a public project ([microsoft/sarif-visualstudio-extension](https://github.com/microsoft/sarif-visualstudio-extension)) and are interested in using this publicly. Thanks!

**Comment by AArnott** [comment]
I'm so glad to hear you're interested in this. 
The NuGet package will be pushed to nuget.org soon. In the meantime it is available on [this public nuget feed](https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=vs-impl&package=Microsoft.VisualStudio.Sdk.TestFramework&protocolType=NuGet&version=16.5.10-beta).

**Comment by AArnott** [comment]
16.5.22-beta is now on nuget.org
