### ISSUE TITLE
Cancelling a VsTask forever hangs

### ISSUE THREAD

**Issue by davkean** [microsoft/vssdktestfx#179]
Very similar to https://github.com/microsoft/vssdktestfx/issues/69, except the repro is the following:

``` C#
    [Fact]
    public async Task CanAwaitCancelled2Task()
    {
        var completionSource = new TaskCompletionSource<bool>();

        IVsTask result = ThreadHelper.JoinableTaskFactory.RunAsyncAsVsTask<bool>(
           VsTaskRunContext.UIThreadNormalPriority,
           async (ct) =>
           {
               await completionSource.Task;  // Comment this out to avoid the hang
               throw new OperationCanceledException();
           });

        await Assert.ThrowsAnyAsync<OperationCanceledException>(
            async () =>
            {
                completionSource.SetResult(true);

                await result;
            });
    }
```

In MockVSTaskCompletionSource, if I comment out this line the hang is avoided:

``` C#
    public void SetCanceled()
    {
        this.taskCompletionSource.SetCanceled();
        this.UnderlyingTask.Cancel();  // Comment out this to avoid the hang
    }

```

I've stepped through this code, but I'm no closer to understanding why commenting out that line fixes this. From all I can see, the only thing that calling this.UnderlyingTask.Cancel does, is trigger the CancellationTokenSource passed to pass the underlying delegate in `VsTaskLibraryHelper.RunAsyncAsVsTask`.

Any ideas?

@AArnott @BertanAygun

**Comment by AArnott** [comment]
I'll take a look.

**Comment by AArnott** [comment]
There is a race condition here. I've seen it pass under a debugger, but it usually hangs. The critical point appears to be whether `result` has already completed when `await result;` is executed.
Still looking...

**Comment by AArnott** [comment]
The continuation was getting canceled... 🤦🏼‍♂️
