### ISSUE TITLE
error CS0103: The name 'SdkTestUtilities' does not exist in the current context

### ISSUE THREAD

**Issue by icnocop** [microsoft/vssdktestfx#195]
Hi.

Thank you for `Microsoft.VisualStudio.Sdk.TestFramework`.

I'm trying to create a unit test for a package created using `Community.VisualStudio.Toolkit`, following the example:

```
    [Fact]
    public async Task LoadPackageAsync()
    {
        SomePackage package = await SdkTestUtilities.LoadPackageAsync<SomePackage>(this.Logger.WriteLine);
        Assert.NotNull(package);
    }
```

But I get the compiler error:
```
error CS0103: The name 'SdkTestUtilities' does not exist in the current context
```

`SdkTestUtilities` was added to this repo on April 16th, 2024, but `Microsoft.VisualStudio.Sdk.TestFramework` v17.6.16 was released on July 10th, 2023, so `SdkTestUtilities` doesn't exist in the latest NuGet package.

Is there a different public NuGet feed with the latest bits?

Thank you.

**Comment by AArnott** [comment]
Good point. I've pushed a new release to nuget.org. Thanks for calling this out.
