### ISSUE TITLE
Does this support NUnit?

### ISSUE THREAD

**Issue by maysonchen-cs** [microsoft/vssdktestfx#27]
Does this support NUnit?  
I have many unit test cases written in NUnit. Migration them seems difficult.

**Comment by AArnott** [comment]
Not directly. But it doesn't directly support MSTest either and folks get by just fine with it. We only added Xunit-specific helpers very recently. Just review either xunit or mstest documentation and do the equivalent thing for NUnit. Once you figure it out, if you'd like to share back, I'd entertain a PR to add NUnit to our docs.

**Comment by maysonchen-cs** [comment]
Follow https://github.com/microsoft/vssdktestfx/blob/main/doc/mstest.md, I successfully run all my cases with NUnit.
We may not really need to add separate attribute class. Manually adding `AssemblySetup.MockServiceProvider.Reset()` to the constructor or  `[SetUp]` section of every test class should also work. 

Add this class to your test folder.
`
using Microsoft.VisualStudio.Sdk.TestFramework;
using NUnit.Framework;

namespace Application.Test
{
    [SetUpFixture]
    public class AssemblySetup
    {
        internal static GlobalServiceProvider MockServiceProvider { get; private set; }

        [OneTimeSetUp]
        public void RunBeforeAnyTests()
        {
            MockServiceProvider = new GlobalServiceProvider();
        }

        [OneTimeTearDown]
        public void RunAfterAnyTests()
        {
            MockServiceProvider.Dispose();
        }

    }
}
` 

Create a attribute class
`
using System;
namespace Application.Test
{
    [AttributeUsage(AttributeTargets.Class)]
    public class TestWithAttribute : Attribute
    {
        public TestWithUnityContainerAttribute()
        {
            AssemblySetup.MockServiceProvider.Reset();
        }
    }
}
 `

Add the attribute annotation to every test class
`
namespace Application
{
    [TestFixture]
    [TestWithAttribute]
    public class AnalysisTest 
    {
       [Test]
        public void Test()
        {
            Assert.AreEqual(1, 1);
        }
    }
}
`

**Comment by AArnott** [comment]
Thank you for sharing. Wanna send a PR that adds an nunit.md doc to the repo, @maysonchen-cs.
