### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by aldanchenko** [microsoft/vssdktestfx#31]
Hello 👋

I'm trying to install it via NuGet. Trying to install `Microsoft.VisualStudio.Sdk.TestFramework`. But getting this error

`Error	NU1101	Unable to find package Microsoft.Internal.VisualStudio.Interop. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org`

Also tried to check it on nuget.org but same issue

<img width="1410" alt="Screenshot 2022-05-25 at 13 53 42" src="https://user-images.githubusercontent.com/7049329/170247060-80cee3c4-233e-4895-a271-2e440de3c19d.png">

<img width="1405" alt="Screenshot 2022-05-25 at 13 53 29" src="https://user-images.githubusercontent.com/7049329/170247010-91d8f10e-750a-4865-8026-6fcc16823a4e.png">

Maybe I'm doing something wrong? Could someone please help?

Best regards,
Alex

**Comment by AArnott** [comment]
See #9
