### ISSUE TITLE
Release Version that Works with Visual Studio 2022?

### ISSUE THREAD

**Issue by rich-newman** [microsoft/vssdktestfx#4]
Would it be possible, please, if you've got a moment, now Visual Studio 2022 is out, to help us VSIX devs and release a built version of the head of the code to NuGet?

I seem to need it for testing a VS2022 VSIX that references v17 of the SDK.  If there's a workaround let me know please.  I have built my own version and it works, but I don't really want to publish that separately on NuGet.

**Comment by AArnott** [comment]
Quite so. I'll get right on that.

**Comment by AArnott** [comment]
Done: https://github.com/microsoft/vssdktestfx/releases/tag/v17.0.15

Thanks for bringing this to my attention.

**Comment by rich-newman** [comment]
Thank you so much, much appreciated

**Comment by rich-newman** [comment]
I spoke too soon.  This fails to install for me with error 'Unable to find package Microsoft.Internal.VisualStudio.Interop.  No packages exist with this id in sources'.  

I think the clue is the 'Microsoft.Internal' bit?

I'm a little confused as to why my build worked though, as that managed to download Microsoft.Internal.VisualStudio.Interop.17.0.0-preview-2-31221-277.  That doesn't fit the constraints for the new package (>=17.0.319), and in any case my own build now fails to install if I have a clear cache, so I'm guessing the package has disappeared for non-Microsoft people.

Am I doing something wrong, or is this broken unless you work at Microsoft??

**Comment by AArnott** [comment]
Oh, that package is available from a public feed, but not nuget.org. When you built from this repo, the nuget.config allowed you to pull down that package. But when I pushed this package to nuget.org with an updated dependency version and you then installed to your own repo, the feed wasn't in your nuget.config file so it can't find it. 
I'm not sure how we should fix this. Let me reactivate the issue to track.

**Comment by reduckted** [comment]
I was able to work around this problem by adding this to my `nuget.config` file (take from the NuGet config in this repository):

```diff
 <?xml version="1.0" encoding="utf-8"?>
 <configuration>
   <packageSources>
     <clear/>
     <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
+    <add key="vs-impl-public" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json" protocolVersion="3" />
+    <add key="vssdk-public" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json" protocolVersion="3" />
   </packageSources>
 </configuration>
```

**Comment by rich-newman** [comment]
@reduckted Yes, thank you, that works as a workaround

**Comment by dhabolt** [comment]
@reduckted I had the same issue and this worked for me as well, thanks for posting that!
